# Generated by Django 4.2.1 on 2025-01-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo_light', models.ImageField(upload_to='logos/')),
                ('logo_dark', models.ImageField(upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Main Info',
                'verbose_name_plural': 'Main Info',
            },
        ),
    ]
