# Generated by Django 4.2.1 on 2025-01-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aboutimages_apartments_counter_locationbenefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Prospects',
                'verbose_name_plural': 'Prospects',
            },
        ),
    ]
